
var data1={"instant_trade":instant_trade,
    "ensure_trade":ensure_trade,
    "query_member_name":query_member_name,
    "query_support_bank_and_limit_list":query_support_bank_and_limit_list,
    "query_account_balance_list":query_account_balance_list,
    "entry_account_offline":entry_account_offline,
    "card_register_apply1":card_register_apply1,
    "card_register_advance":card_register_advance,
    "card_register_query":card_register_query,
    "card_register_abandon":card_register_abandon,
    "certification_pay":certification_pay,
    "certification_pay_confirm":certification_pay_confirm,
    "agreement_pay_confirm":agreement_pay_confirm,
    "card_register_and_pay":card_register_and_pay,
    "card_register_and_pay_confirm":card_register_and_pay_confirm,
    "card_register_apply":card_register_apply,
    "trade_refund":trade_refund,
    "trade_close":trade_close,
    "trade_query":trade_query,
    "card_bin_query":card_bin_query,
    "transfer_to_external":transfer_to_external,
    "trade_bank_witholding":trade_bank_witholding,
    "fund_purchase_balance":fund_purchase_balance,
    "transfer_to_card":transfer_to_card,
    "batch_transfer_card":batch_transfer_card,
    "transfer_to_account":transfer_to_account,
    "batch_transfer_account":batch_transfer_account,
    "sub_merchant_registration":sub_merchant_registration,
    "resubmission_information":resubmission_information,
    "sub_merchant_registered_query":sub_merchant_registered_query,
    "sub_merchant_change_bankcard":sub_merchant_change_bankcard,
    "sub_merchant_change_bankcard_query":sub_merchant_change_bankcard_query,
    "sub_merchant_change_settle_type":sub_merchant_change_settle_type,
    "sub_merchant_withdrawal_cash":sub_merchant_withdrawal_cash,
    "query_balance_by_account_type":query_balance_by_account_type,
    "query_sub_merchant_bankcard_info":query_sub_merchant_bankcard_info,
    "sub_merchant_permission_apply":sub_merchant_permission_apply,
    "sub_merchant_permission_apply_query":sub_merchant_permission_apply_query,
    "qrcode_apply":qrcode_apply,
    "qrcode_apply_query":qrcode_apply_query,
};


var enToCN={"instant_trade":"即时到账",
    "ensure_trade":"担保交易",
    "query_member_name":"会员名称查询",
    "query_support_bank_and_limit_list":"限额查询",
    "query_account_balance_list":"余额查询",
    "entry_account_offline":"登帐服务网关接口",
    "card_register_apply1":"协议支付-签约触发短信验证",
    "card_register_advance":"协议支付-签约确认",
    "card_register_query":"协议支付-签约结果查询",
    "card_register_abandon":"协议支付-解约",
    "certification_pay":"协议支付-支付申请",
    "certification_pay_confirm":"协议支付--支付确认",
    "agreement_pay_confirm":"支付确认--新接口",
    "card_register_and_pay":"协议支付- 签约并支付申请",
    "card_register_and_pay_confirm":"协议支付- 签约并支付确认",
    "card_register_apply":"认证支付",
    "trade_refund":"退款接口",
    "trade_close":"交易关闭接口",
    "trade_query":"交易查询接口",
    "card_bin_query":"银行卡bin查询接口",
    "transfer_to_external":"外场转账接口",
    "trade_bank_witholding":"银行卡代扣",
    "fund_purchase_balance":"余额申购基金",
    "transfer_to_card":"转账到银行卡",
    "batch_transfer_card":"批量转账到银行卡",
    "transfer_to_account":"转账到账户",
    "batch_transfer_account":"批量转账到账户",
    "sub_merchant_registration":"子商户注册",
    "resubmission_information":"准入资料重提网关接口",
    "sub_merchant_registered_query":"子商户注册查询",
    "sub_merchant_change_bankcard":"子商户结算银行账户变更",
    "sub_merchant_change_bankcard_query":"子商户结算银行账户变更查询网关接口",
    "sub_merchant_change_settle_type":"子商户结算方式变更网关接口",
    "sub_merchant_withdrawal_cash":"子商户主动提现网关接口",
    "query_balance_by_account_type":"查询指定账户余额网关接口",
    "query_sub_merchant_bankcard_info":"子商户结算银行卡信息查询网关接口",
    "sub_merchant_permission_apply":"申请子商户权限网关接口",
    "sub_merchant_permission_apply_query":"子商户权限申请查询网关接口",
    "qrcode_apply":"扫码进件接口",
    "qrcode_apply_query":"扫码进件接口查询",
};


var paymethod={"网银页面":unionpay,
    "条码-主扫":WECHAT,
    "条码-公众号":WECHATSMQ,
    "余额支付":WECHATAPP,
    "基金支付":WECHATH5,
    "协议支付":ALIPAY,
    "直接支付":ALIPAYSMQ,
    "收银台": null
};